remote_theme: just-the-docs/just-the-docs@v0.9.0

plugins:
  - jekyll-seo-tag

title: "Tuufless's FFXIV Notes"
description: "Raiding in FFXIV JP data centers"

favicon_ico: "favicon.ico"

color_scheme: dark

aux_links:
  "Elemental DC Raid Macros Discord":
    - "https://discord.gg/WEzhVHwAU6"
  "Github":
    - "https://github.com/Tuufless/FFXIV-Elemental-raid-macros"

aux_links_new_tab: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

collections:
  elemental:
    permalink: "/:collection/:path/"
    output: true
  mana:
    permalink: "/:collection/:path/"
    output: true
  static:
    permalink: "/:collection/:path/"
    output: true

# The order and names here determines the order in the sidebar
just_the_docs:
  collections:
    elemental:
      name: Ultimates (Elemental)
    mana:
      name: Ultimates (Mana)
    static:
      name: Static
